const $=s=>document.querySelector(s), get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let user=null,active=null;
function show(x){$("#login").classList.toggle("hidden",x!=="login");$("#register").classList.toggle("hidden",x!=="register")} window.show=show;
$("#register").onsubmit=e=>{e.preventDefault();if($("#ic").value!=="PSSS-2026")return $("#msg").textContent="Einladungscode falsch";let u=get("users",[]),name=$("#ru").value.trim().toLowerCase();if(u.some(x=>x.u===name))return $("#msg").textContent="Benutzername vergeben";u.push({u:name,p:$("#rp").value,n:$("#dn").value.trim()});set("users",u);$("#lu").value=name;show("login");$("#msg").textContent="Konto erstellt"};
$("#login").onsubmit=e=>{e.preventDefault();let x=get("users",[]).find(x=>x.u===$("#lu").value.trim().toLowerCase()&&x.p===$("#lp").value);if(!x)return $("#msg").textContent="Login falsch";login(x)};
function chats(){return get("chats_"+user.u,[])} function saveChats(v){set("chats_"+user.u,v)} function msgs(id){return get("msgs_"+user.u+"_"+id,[])}
function login(x){user=x;set("session",x.u);$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");$("#me").textContent=x.n||x.u;if(!chats().length)saveChats([{id:crypto.randomUUID(),type:"group",name:"Testgruppe",members:["Andreas","Steffi","Martin"]}]);render()}
$("#logout").onclick=()=>{localStorage.removeItem("session");location.reload()}
function render(){let c=chats();$("#list").innerHTML=c.map(x=>`<div class="item" data-id="${x.id}"><b>${x.name}</b><div class="badge">${x.type==="group"?"Gruppe · "+x.members.length+" Mitglieder":"Einzelchat"}</div></div>`).join("");document.querySelectorAll(".item").forEach(i=>i.onclick=()=>open(i.dataset.id))}
function open(id){active=id;let c=chats().find(x=>x.id===id);$("#empty").classList.add("hidden");$("#panel").classList.remove("hidden");$("#title").textContent=c.name;$("#meta").textContent=c.type==="group"?c.members.join(", "):"Einzelchat";renderMsgs()}
function renderMsgs(){let a=msgs(active);$("#messages").innerHTML=a.map(m=>`<div class="m ${m.mine?"mine":""}">${m.sender?`<small>${m.sender}</small><br>`:""}${m.text}</div>`).join("")}
$("#send").onsubmit=e=>{e.preventDefault();let t=$("#text").value.trim();if(!t||!active)return;let a=msgs(active),c=chats().find(x=>x.id===active);a.push({text:t,mine:true,sender:c.type==="group"?(user.n||user.u):""});set("msgs_"+user.u+"_"+active,a);$("#text").value="";renderMsgs()}
$("#friendBtn").onclick=()=>$("#friendDlg").showModal();$("#saveFriend").onclick=e=>{e.preventDefault();let n=$("#friendName").value.trim();if(!n)return;let c=chats();c.push({id:crypto.randomUUID(),type:"friend",name:n,members:[n]});saveChats(c);$("#friendDlg").close();render()}
$("#groupBtn").onclick=()=>$("#groupDlg").showModal();$("#saveGroup").onclick=e=>{e.preventDefault();let n=$("#groupName").value.trim();if(!n)return;let m=$("#members").value.split(",").map(x=>x.trim()).filter(Boolean);m.unshift(user.n||user.u);let c=chats();c.push({id:crypto.randomUUID(),type:"group",name:n,members:m});saveChats(c);$("#groupDlg").close();render()}
let s=get("session",null);if(s){let x=get("users",[]).find(x=>x.u===s);if(x)login(x)}
